### ISSUE TITLE
[MVE export] convert ID to indexes

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#136]
MVE only supports indexes.

**Comment by pmoulon** [comment]
can you be more explicit?

**Comment by fabiencastan** [comment]
MVE use indexes as we can see here:
https://github.com/simonfuhrmann/mve/blob/master/libs/mve/scene.cc#L184

They use an std::vector of views. They support with some missing indexes but cannot support custom IDs as we can do in openMVG. So we should probably do the same than what is done in CMPMVS export: ignore the view ids and export a list of views with indexes.

What do you think of it?

**Comment by pmoulon** [comment]
The MVE2 exporter do already the job (only valid view are exported).
Since default openMVG init the ID from 0 to n, it's not a problem.
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2MVE2.cpp#L106

But if you add your custom ID you should use a map to reindex the view ID from 0 to n.
You will loose the ID matching from openMVG to MVE...
