### ISSUE TITLE
Evaluation of SIFT descriptors: uchar vs float

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#26]

**Comment by pmoulon** [comment]
It can be done easily on some repeatability evaluation:
https://github.com/openMVG/openMVG/tree/develop/src/openMVG_Samples/features_repeatability => runs on https://github.com/openMVG/Features_Repeatability

But results on tiny image dataset and large dataset could be different. Since quantization effect will not have the same impact...

**Comment by fabiencastan** [comment]
Could be closed?
